group = "(" term ")" ;

term = term = factor ( ( "+" | "-" ) factor)* ;
factor = exponentiation  ( ( "*" | "/" | "%" ) exponentiation )*
exponentiation = negation ( ( "^" ) exponentiation )* ;
negation = "-" NUMBER ;